#%RAML 1.0
---
title: "Dotsby API Doc"
version: v1
protocols: [HTTPS]
mediaType: application/json

annotationTypes:
  serviceName:
    type: string
    description: API service catalog
    allowedTargets: Resource
  exampleString:
    type: string
    description: example string

securitySchemes:
  token:
    description: |
      API request need carry valid token obtained from [CreateToken](/auth/auth.createToken) API
    type: token
    describedBy:
      headers:
        Authorization:
          description: Token fetching through Login Api
          type: string
      responses:
        401:
          body:
            type: object
            properties:
              data:
                type: object
                properties:
                  code: string
                  message: string
          description: |
            bad or expired token.


traits:
  hasHeaders:
    headers:
      Content-type:
        displayName: Content-type
        description: either xml or json
        type: string
        required: true
  caller_error:
    usage: Apply to method for generating caller side error
    responses:
      400:
        body:
          type: ResponseError
        description: caller side error, primary for incorret parameters
  paged:
    usage: Apply to .list method for pagination response
    queryParameters:
      page?:
        description: Specify the page that you want to retrieve
        type: integer
        default: 1
      limit?:
        description: Specify the amount of items that will be retrieved per page
        type: integer
        default: 10
    responses:
      200:
        body:
          type: object
          properties:
            pagination:
              type: object
              properties:
                page:
                  type: integer
                  description: current page number
                pages:
                  type: integer
                  description: total page number
                limit:
                  type: integer
                  description: the amount of items per page
                count:
                  type: integer
                  description: Total count of all data items

## User
/user/signup:
  post:
    displayName: Sign Up
    body:
      type: !include ./schemas/apis/user_signup_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/user_signup_response.json
/user/login:
  post:
    displayName: Login
    body:
      type: !include ./schemas/apis/user_login_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/user_login_response.json
/user/logout:
  post:
    displayName: Logout
    securedBy: ["token"]
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/user_logout_response.json
/user/info:
  get:
    displayName: Get User Info
    securedBy: ["token"]
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/user_info_response.json

## Document
/document/create:
  post:
    displayName: Create Document
    body:
      type: !include ./schemas/apis/document_create_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/document_create_response.json
/document/publish:
  post:
    displayName: Publish Document
    securedBy: ["token"]
    body:
      type: !include ./schemas/apis/document_publish_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/document_publish_response.json
/document/list:
  get:
    displayName: List Document
    securedBy: ["token"]
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/document_list_response.json
/document:
  get:
    displayName: Get Document Info
    queryParameters:
      type: !include ./schemas/apis/document_info_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/document_info_response.json

## Page
/page:
  get:
    displayName: Get Page Info
    queryParameters:
      type: !include ./schemas/apis/page_info_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/page_info_response.json

## Query
/query:
  get:
    displayName: Keyword Query
    queryParameters:
      type: !include ./schemas/apis/query_params.json
    responses:
      200:
        body:
          type: object
          properties:
            data:
              type:  !include ./schemas/apis/query_response.json