#%RAML 1.0
---
title: "Dotsby API"
version: v1
protocols: [HTTPS]
mediaType: application/json

annotationTypes:
  serviceName:
    type: string
    description: API service catalog
    allowedTargets: Resource
  exampleString:
    type: string
    description: example string

securitySchemes:
  token:
    description: |
      API request need carry valid token obtained from [CreateToken](/auth/auth.createToken) API
    type: x-token
    describedBy:
      headers:
        X-TOKEN:
          description: Token fetching through Login Api
          type: string
        X-TOKEN2:
          description: Token fetching through Github Api
          type: string
      responses:
        401:
          body:
            type: ResponseError
          description: |
            bad or expired token. This can happen if the AppUser
            revoked token or this token had already expired or
            submitted token not suited to this API.
            To fix, generate the token through Auth API again.

            Another situation is that the token is not formed in a valid syntax
            or the token value is just missing.


traits:
  hasHeaders:
    headers:
      Authorization:
        displayName: Authorization
        description: Basic authentication base 64 encoded string
        type: string
        required: true
      Content-type:
        displayName: Content-type
        description: either xml or json
        type: string
        required: true
  caller_error:
    usage: Apply to method for generating caller side error
    responses:
      400:
        body:
          type: ResponseError
        description: caller side error, primary for incorret parameters
  paged:
    usage: Apply to .list method for pagination response
    queryParameters:
      page?:
        description: Specify the page that you want to retrieve
        type: integer
        default: 1
      limit?:
        description: Specify the amount of items that will be retrieved per page
        type: integer
        default: 10
    responses:
      200:
        body:
          type: object
          properties:
            pagination:
              type: object
              properties:
                page:
                  type: integer
                  description: current page number
                pages:
                  type: integer
                  description: total page number
                limit:
                  type: integer
                  description: the amount of items per page
                count:
                  type: integer
                  description: Total count of all data items

## Document
/document/token:
  get:
    displayName: Get Document Token
    securedBy: ["token", "token2"]
    is: ["hasHeaders", "paged"]
    headers:
      Some-Id:
        displayName: Some-Id
        description: Some-Id Example
        type: string
        required: true
    queryParameters:
      id:
        type: string
        description: ID of account
    body:
      id:
        type: string
        description: ID of user
      account_id:
        type: string
        description: ID of account
      flat_body:
        type: object
        properties:
          id:
            type: string
            description: ID of user
          example_id:
            type: string
            description: ID of example
      flat_body2:
        type: object
        properties:
          data:
            type: !include ./schemas/apis/document_publish_params.json
    responses:
      200:
        body:
          # type:  !include ./schemas/apis/document_publish_params.json
          type: object
          properties:
            data:
              type: array
              items: !include ./schemas/apis/document_publish_params.json
        headers:
          X-Some-Header:
            description: |
              HTTP Custom Parameter
              Some description.
            type: datetime
            required: false
            example: 2017-12-31T23:59:59.0+01:00